- pom.xml
- src/main/java/org/folio/rest/impl/AuditDataImpl.java
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/impl/AuditDataImplTest.java
Upgraded mod-audit to RMB v30.0.2 and made related changes. Also performed some clean ups as prompted by the IDE.
> RMB 30.0.2 upgrade

- NEWS.md
- pom.xml
Added an entry to NEWS.md and incremented the next version number in pom.xml
> Releasing mod-audit

- ramls/examples/logRecord.sample.json
- ramls/examples/logRecordCollection.sample.json
- ramls/logRecord.json
- ramls/logRecordCollection.json
[MODAUD-9](https://issues.folio.org/browse/MODAUD-9) - Create LogRecord schema
* logRecord schema and example are created
Validated on [Json schema validator](https://www.jsonschemavalidator.net)
> MODAUD-9 - Create LogRecord schema

- src/main/resources/templates/db_scripts/schema.json
[MODAUD-12](https://issues.folio.org/browse/MODAUD-12) - Prepare DB tables for Circulation Audit Logs
Tables were created:
> MODAUD-12 - Prepare DB tables for Circulation Audit Logs

- .rancher-pipeline.yml
+ @celticmask 
Could you please verify?
Pipeline successfully completed https://rancher.dev.folio.org/p/c-cv652:p-ngvqv/pipeline/pipelines/p-ngvqv:p-ls57r/run/6?group=namespace
> Rancher pipeline for mod-audit

- ramls/examples/logRecord.sample.json
- ramls/examples/logRecordCollection.sample.json
- ramls/logRecord.json
- src/main/resources/samples/fee_fine.json
- src/main/resources/samples/item_block.json
- src/main/resources/samples/loan.json
- src/main/resources/samples/manual_block.json
- src/main/resources/samples/notice.json
- src/main/resources/samples/patron_block.json
- src/main/resources/samples/request.json
- src/test/java/org/folio/rest/impl/CirculationLogsImplTest.java
[MODAUD-10](https://issues.folio.org/browse/MODAUD-10) - GET /audit-data/logs for Circulation Audit Logs
* changed logRecord schema
* updated sample data
> MODAUD-10 - GET /audit-data/logs for Circulation Audit Logs

- mod-audit-server/src/main/resources/samples/fee_fine.json
- mod-audit-server/src/main/resources/samples/item_block.json
- mod-audit-server/src/main/resources/samples/loan.json
- mod-audit-server/src/main/resources/samples/manual_block.json
- mod-audit-server/src/main/resources/samples/notice.json
- mod-audit-server/src/main/resources/samples/patron_block.json
- mod-audit-server/src/main/resources/samples/request.json
- mod-audit-server/src/main/resources/templates/db_scripts/schema.json
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditHandlersImplTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/CirculationLogsImplTest.java
- ramls/examples/logRecord.sample.json
- ramls/examples/logRecordCollection.sample.json
- ramls/logRecord.json
> MODAUD-TD-PUBSUB - Technical Debt: PubSub integration

- mod-audit-server/src/main/resources/samples/notice.json
https://issues.folio.org/browse/MODAUD-21
While it's helpful for reviewers to help …
> MODAUD-21 Update samples data: several items for notice

- NEWS.md
- mod-audit-server/pom.xml
- pom.xml
[MODAUD-22](https://issues.folio.org/browse/MODAUD-22) - Release 1.0.0
> MODAUD-22 - Release 1.0.0

- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/test/resources/payloads/loan.json
[MODAUD-29](https://issues.folio.org/browse/MODAUD-29) - Template name in Notices log description and Source filed in Loan log record are empty
Template name in Notices log description and Source field in Loan log record should be resolved and saved in log record
Call to Users and Templates APIs for retrieving data
Ideally all of the PRs involved in …
> MODAUD-29 - Template name in Notices log description and Source filed in Loan log record are empty

- NEWS.md
- descriptors/ModuleDescriptor-template.json
[MODAUD-33](https://issues.folio.org/browse/MODAUD-33) - Release 1.0.1
NEWS.md, ModuleDescriptor updating
> MODAUD-33 - Release 1.0.1 (updating master)

- mod-audit-server/pom.xml
- pom.xml
[MODAUD-34](https://issues.folio.org/browse/MODAUD-34) - mod-audit: RMB Update
Updating RMB to 31.1.5
Updating version in accordance with https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-310
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
> MODAUD-34 - mod-audit: RMB Update

- NEWS.md
- mod-audit-server/pom.xml
- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/test/resources/payloads/loan.json
- pom.xml
[MODAUD-33](https://issues.folio.org/browse/MODAUD-33) - Release 1.0.2
> MODAUD-33 - Release-1.0.2

- NEWS.md
[MODAUD-33](https://issues.folio.org/browse/MODAUD-33) - Release 1.0.2
NEWS.md
> MODAUD-33 - Release-1.0.2 (updating master)

- mod-audit-server/src/main/java/org/folio/builder/service/FeeFineRecordBuilder.java
- mod-audit-server/src/test/java/org/folio/builder/service/FeeFineRecordBuilderTest.java
- mod-audit-server/src/test/resources/payloads/fee_fine_billed.json
[MODAUD-41](https://issues.folio.org/browse/MODAUD-41) - Fees/fines records in Circulation log do not contain item details
Fees/fines log records should contain necessary item info to provide item details
* Leveraged Inventory API to fetch item data
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
> MODAUD-41 - Fees/fines records in Circulation log do not contain item details

- mod-audit-server/src/main/java/org/folio/builder/LogRecordBuilderResolver.java
- mod-audit-server/src/main/java/org/folio/builder/description/RequestDescriptionBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/RequestRecordBuilder.java
- mod-audit-server/src/test/java/org/folio/TestBase.java
- mod-audit-server/src/test/java/org/folio/builder/service/RequestRecordBuilderTest.java
- mod-audit-server/src/test/resources/payloads/request_expired.json
[MODAUD-44](https://issues.folio.org/browse/MODAUD-44) - Update mod-audit requests to handle REQUEST_EXPIRED_EVENT
New event type REQUEST_EXPIRED_EVENT was introduced in the story https://issues.folio.org/browse/CIRCSTORE-247. Mod-audit log records for requests should be updated to handle and log this event.
Added required event handler
Ideally all of …
> MODAUD-44 - Update mod-audit requests to handle REQUEST_EXPIRED_EVENT

- PERSONAL_DATA_DISCLOSURE.md
- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
Place a copy of the personal data disclosure form at the top level of the module github repository to disclose stored types of personal data
- added PERSONAL_DATA_DISCLOSURE.md file
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
> MODAUD-51 - Add personal data disclosure form

- mod-audit-server/src/main/java/org/folio/builder/LogRecordBuilderResolver.java
- mod-audit-server/src/main/java/org/folio/builder/service/RequestRecordBuilder.java
- mod-audit-server/src/test/java/org/folio/TestBase.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditHandlersImplApiTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/CirculationLogsImplApiTest.java
- mod-audit-server/src/test/resources/payloads/request_created_through_override.json
- ramls/schemas/action_type.json
Implement support for **LOG_RECORD** events with event type **REQUEST_CREATED_THROUGH_OVERRIDE_EVENT** published by mod-circulation whenever a request is created through override (see [CIRC-1063](https://issues.folio.org/browse/CIRC-1063) for details). Log records created with this event type are identical to those with type REQUEST_CREATED, with only difference in the value of `action` property : it has to be `Created through override` instead of just `Created` (see [UIREQ-576](https://issues.folio.org/browse/UIREQ-576)).
- …
> [MODAUD-57] Implement support for REQUEST_CREATED_THROUGH_OVERRIDE_EVENT

- mod-audit-server/src/main/java/org/folio/rest/impl/ModTenantService.java
- mod-audit-server/src/test/java/org/folio/rest/impl/ApiTestBase.java
Improvements and optimization of [PR#69](https://github.com/folio-org/mod-audit/pull/69).
> MODAUD-47 - mod-audit: RMB Update

- NEWS.md
- mod-audit-server/pom.xml
- pom.xml
[MODAUD-45](https://issues.folio.org/browse/MODAUD-45) - MODAUD (mod-audit) release
> MODAUD-45 - MODAUD (mod-audit) release

- mod-audit-server/pom.xml
- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/rest/impl/AuditHandlersService.java
- mod-audit-server/src/test/java/org/folio/builder/service/RequestRecordBuilderTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditHandlersImplApiTest.java
- mod-audit-server/src/test/resources/mock_content.json
[MODAUD-54](https://issues.folio.org/browse/MODAUD-54) - Click on item barcode results in error message
Fixing generic issue with events handling due to http client closing before future completing.
Improvements of handleGetRequest method.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
> MODAUD-54 - Click on item barcode results in error message

- mod-audit-server/src/main/java/org/folio/builder/description/ManualBlockDescriptionBuilder.java
- mod-audit-server/src/test/java/org/folio/builder/service/ManualBlockRecordBuilderTest.java
- mod-audit-server/src/test/resources/payloads/manual_block_deleted.json
- mod-audit-server/src/test/resources/payloads/manual_block_updated.json
[MODAUD-64](https://issues.folio.org/browse/MODAUD-64) - Filter circulation log on description is not working
Minor improvements for description format
Description formatting update.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …
> MODAUD-64 - Filter circulation log on description is not working

- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/NoticeRecordBuilder.java
- mod-audit-server/src/test/java/org/folio/builder/service/NoticeRecordBuilderTest.java
- mod-audit-server/src/test/resources/mock_content.json
- mod-audit-server/src/test/resources/payloads/notice.json
[MODAUD-66](https://issues.folio.org/browse/MODAUD-66) - User ID is `undefined` for Notice entries
Loss userIf fixing
Retrieve user by barcode and extract id.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> MODAUD-66 - User ID is `undefined` for Notice entries

- mod-audit-server/src/main/java/org/folio/builder/service/LoanRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/NoticeRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/rest/impl/AuditHandlersService.java
- mod-audit-server/src/main/java/org/folio/rest/impl/BaseService.java
- mod-audit-server/src/main/java/org/folio/rest/impl/CirculationLogsService.java
- mod-audit-server/src/main/resources/templates/db_scripts/schema.json
- mod-audit-server/src/test/java/org/folio/builder/service/LoanRecordBuilderTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/CirculationLogsImplApiTest.java
- mod-audit-server/src/test/java/org/folio/utils/TenantApiTestUtil.java
- mod-audit-server/src/test/resources/mock_content.json
- mod-audit-server/src/test/resources/mocks/anonymize_item.json
- mod-audit-server/src/test/resources/payloads/anonymize_check_in.json
- mod-audit-server/src/test/resources/payloads/anonymize_check_out.json
- mod-audit-server/src/test/resources/payloads/anonymize_loan.json
- mod-audit-server/src/test/resources/payloads/anonymize_loan_closed.json
[MODAUD-58](https://issues.folio.org/browse/MODAUD-58) - Incomplete anonymization in Circulation log
Anonymizing a loan in Circulation log does not anonymize all aspects of the loan.
All user data now being deleted from all records related to loan.
Verified on local testing environment:
* before anonymization:
* after anonymization:
Ideally all of the …
> MODAUD-58 - Incomplete anonymization in Circulation log

- mod-audit-server/src/main/java/org/folio/builder/service/LoanRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/util/LogEventPayloadField.java
- mod-audit-server/src/test/java/org/folio/builder/service/LoanRecordBuilderTest.java
[MODAUD-73](https://issues.folio.org/browse/MODAUD-73) - Fixing source name for Loan records
Invalid source name in the log record entry.
Changing retrieving user for loans from updatedByUserId to userId
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
> MODAUD-73 - Fixing source name for Loan records

- mod-audit-server/src/main/java/org/folio/builder/LogRecordBuilderResolver.java
- mod-audit-server/src/main/java/org/folio/builder/service/CheckOutRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/test/java/org/folio/builder/service/BuilderTestBase.java
- mod-audit-server/src/test/java/org/folio/builder/service/CheckOutRecordBuilderTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditHandlersImplApiTest.java
- mod-audit-server/src/test/java/org/folio/utils/TenantApiTestUtil.java
- mod-audit-server/src/test/resources/payloads/check_out_through_override.json
[MODAUD-77](https://issues.folio.org/browse/MODAUD-77)
Enable check out through override support
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> MODAUD-77 - Check out through override support

- NEWS.md
- mod-audit-server/src/main/java/org/folio/builder/LogRecordBuilderResolver.java
- mod-audit-server/src/main/java/org/folio/builder/service/CheckOutRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/test/java/org/folio/builder/service/BuilderTestBase.java
- mod-audit-server/src/test/java/org/folio/builder/service/CheckOutRecordBuilderTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditHandlersImplApiTest.java
- mod-audit-server/src/test/java/org/folio/utils/TenantApiTestUtil.java
- mod-audit-server/src/test/resources/payloads/check_out_through_override.json
[MODAUD-78](https://issues.folio.org/browse/MODAUD-78) - Bugfix release 2.0.4
> MODAUD-78 - Release 2.0.4

- mod-audit-server/pom.xml
- mod-audit-server/src/main/java/org/folio/builder/description/DescriptionHelper.java
- mod-audit-server/src/main/java/org/folio/builder/description/FeeFineDescriptionBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/description/LoanCheckInDescriptionBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/description/RequestDescriptionBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/FeeFineRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/NoticeRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/util/JsonPropertyFetcher.java
- mod-audit-server/src/test/java/org/folio/TestSuite.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditDataImplApiTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/CirculationLogsImplApiTest.java
- mod-audit-server/src/test/java/org/folio/utils/TenantApiTestUtil.java
- pom.xml
[MODAUD-60](url) - Update RMB version
Update RMB version to 33.0.0.
- Make necessary changes in pom.xml files (both of mod-audit and mod-audit-server)
- Make necessary changes in java code:
* replace joda time with java time
* replace org.apache.commons.lang with org.apache.commons.lang3
* replace EmbeddedPostgres with PostgresTesterContainer
* reduce using org.folio.rest.tools.utils package since deprecated
- remove deprecated
- update logic for client
- Do JIRAs exist to …
> MODAUD-60 - Updated raml-module-builder to version 33.0.0

- mod-audit-server/pom.xml
- mod-audit-server/src/main/java/org/folio/builder/description/DescriptionHelper.java
- mod-audit-server/src/main/java/org/folio/builder/description/FeeFineDescriptionBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/description/LoanCheckInDescriptionBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/description/RequestDescriptionBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/FeeFineRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/NoticeRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/util/JsonPropertyFetcher.java
- mod-audit-server/src/test/java/org/folio/TestSuite.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditDataImplApiTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/CirculationLogsImplApiTest.java
- mod-audit-server/src/test/java/org/folio/utils/TenantApiTestUtil.java
- pom.xml
Reverts folio-org/mod-audit#90
> Revert "MODAUD-60 - Updated raml-module-builder to version 33.0.0"

- pom.xml
[MODAUD-83](https://issues.folio.org/browse/MODAUD-83) - Update mod-pubsub-client dependency to v2.3.0
mod-pubsub-client 2.1.0 will not create module ID in a proper format - module-name-1.2.3. It's not able to determine the correct module version.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
> MODAUD-83 Update mod-pubsub-client version

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- mod-audit-server/pom.xml
- pom.xml
[MODAUD-59](https://issues.folio.org/browse/MODAUD-59) - MODAUD (mod-audit) release
> MODAUD-59 - 2.1.0 RELEASE

- mod-audit-server/src/main/java/org/folio/builder/service/LoanRecordBuilder.java
- mod-audit-server/src/test/java/org/folio/builder/service/LoanRecordBuilderTest.java
- mod-audit-server/src/test/java/org/folio/utils/TenantApiTestUtil.java
- mod-audit-server/src/test/resources/payloads/loan_changed_due_date.json
[MODAUD-90](https://issues.folio.org/browse/MODAUD-90) - Screen is hanging on a loading screen when trying to view loan details on the Circulation log page
If the user filters by "Recall requested" in the "Loans" section of the Circulation log page, then scroll to the right and select "Loan details" on the ellipses in the "Action" column, the screen is hanging on a loading screen.
* updated loan builder logic
* updated unit test
- …
> MODAUD-90 - Screen is hanging on a loading screen when trying to view loan details on the Circulation log page

- mod-audit-server/src/main/java/org/folio/builder/service/ManualBlockRecordBuilder.java
- mod-audit-server/src/test/java/org/folio/builder/service/ManualBlockRecordBuilderTest.java
[MODAUD-38](https://issues.folio.org/browse/MODAUD-38) - Source for ManualBlock deleting
Log record for manual block deleting should contain source with user name who deleted this manual block.
Enable source when event is manual_block_deleted (it was disabled).
[APPROACH 1](https://wiki.folio.org/pages/viewpage.action?spaceKey=FOLIJET&title=User+name+during+manual+block+deleting)
- Do …
> MODAUD-38 - Source for ManualBlock deleting

- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/test/java/org/folio/builder/service/NoticeRecordBuilderTest.java
- mod-audit-server/src/test/java/org/folio/utils/TenantApiTestUtil.java
- mod-audit-server/src/test/resources/mock_content.json
- mod-audit-server/src/test/resources/payloads/notice_error_non_existent_user_id.json
Fix NPE when attempting to create log record for NOTICE_ERROR event with non-existent user ID.
Resolves [MODAUD-86](https://issues.folio.org/browse/MODAUD-86).
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> [MODAUD-86] Create records for NOTICE_ERROR events with non-existent user ID

- NEWS.md
- mod-audit-server/pom.xml
- pom.xml
[MODAUD-80](https://issues.folio.org/browse/MODAUD-80) - MODAUD (mod-audit) release
> MODAUD-80 - 2.2.0-RELEASE

- mod-audit-server/src/main/java/org/folio/rest/impl/AuditHandlersService.java
[MODAUD-95](https://issues.folio.org/browse/MODAUD-95) - Improve logging
Improve logging.
Add more detailed error message.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> MODAUD-95 - Improve logging

- mod-audit-server/src/main/java/org/folio/builder/service/LoanRecordBuilder.java
- mod-audit-server/src/test/java/org/folio/builder/service/LoanRecordBuilderTest.java
- mod-audit-server/src/test/java/org/folio/utils/TenantApiTestUtil.java
- mod-audit-server/src/test/resources/payloads/loan_charge_lost_fees.json
- ramls/schemas/action_type.json
[MODAUD-93](https://issues.folio.org/browse/MODAUD-93) - Error logging is missing key information
Add Charge lost fees action.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> MODAUD-93 - Error logging is missing key information

- pom.xml
[MODAUD-97](https://issues.folio.org/browse/MODAUD-97) - Kiwi R3 2021 - Log4j vulnerability verification and correction
> MODAUD-97 - Kiwi R3 2021 - Log4j vulnerability verification and correction

- NEWS.md
- mod-audit-server/pom.xml
- pom.xml
[MODAUD-101](https://issues.folio.org/browse/MODAUD-101) - MODAUD (mod-audit) Kiwi Bugfix release
> MODAUD-101 - MODAUD (mod-audit) Kiwi Bugfix release

- NEWS.md
- mod-audit-server/pom.xml
- pom.xml
[MODAUD-102](https://issues.folio.org/browse/MODAUD-102) - MODAUD (mod-audit) Juniper Hotfix release
> MODAUD-102 - MODAUD (mod-audit) Juniper Hotfix release

- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/rest/impl/AuditHandlersService.java
- mod-audit-server/src/test/java/org/folio/builder/service/LoanRecordBuilderTest.java
[MODAUD-93](https://issues.folio.org/browse/MODAUD-93) - Error logging is missing key information
Improve logging, fix bugs.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> MODAUD-93 Improve logging

- mod-audit-server/pom.xml
- pom.xml
[MODAUD-108](https://issues.folio.org/browse/MODAUD-108) - Release 2.3.0 (bump up artefact version to 2.4.0-SNAPSHOT)
> MODAUD-108 - Release 2.3.0

- pom.xml
[MODAUD-119](https://issues.folio.org/browse/MODAUD-119) - Spring4Shell Morning Glory R2 2022 (CVE-2022-22965)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> MODAUD-119 - Spring4Shell Morning Glory R2 2022 (CVE-2022-22965)

- README.md
- pom.xml
[MODAUD-118](https://issues.folio.org/browse/MODAUD-118) - Spring4Shell Lotus R1 2022 (CVE-2022-22965)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> MODAUD-118 - Spring4Shell Lotus R1 2022 (CVE-2022-22965)

- mod-audit-server/pom.xml
- pom.xml
Need upgrade version of module to 2.5.0-SNAPSHOT as there is release with version 2.4.0 for Lotus HotFix
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> Bump-up artifact version

- NEWS.md
- mod-audit-server/pom.xml
- pom.xml
[MODAUD-120](https://issues.folio.org/browse/MODAUD-120) - MODAUD (mod-audit) Lotus HF#1 release
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> MODAUD-120 - Release 2.4.0

- mod-audit-server/pom.xml
- mod-audit-server/src/test/java/org/folio/rest/impl/CirculationLogsImplApiTest.java
- pom.xml
[MODAUD-111](https://issues.folio.org/browse/MODAUD-111) - RMB v34 upgrade - Morning Glory 2022 R2 module release
Upgrade RMB version to 34.0.0
* Updated RMB version to 34.0.0
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> MODAUD-111 - RMB v34 upgrade - Morning Glory 2022 R2 module release

- NEWS.md
- mod-audit-server/pom.xml
- pom.xml
[MODAUD-103](https://issues.folio.org/browse/MODAUD-103) - MODAUD (mod-audit) Iris Hotfix release
> MODAUD-103 - MODAUD (mod-audit) Iris Hotfix release

- NEWS.md
- mod-audit-server/pom.xml
- pom.xml
[MODAUD-109](https://issues.folio.org/browse/MODAUD-109) - Release 2.5.0
> MODAUD-109 - Release 2.5.0

- mod-audit-server/src/main/java/org/folio/rest/impl/CirculationLogsService.java
- mod-audit-server/src/main/java/org/folio/util/Constants.java
- mod-audit-server/src/test/java/org/folio/rest/impl/CirculationLogsImplApiTest.java
[MODAUD-131](https://issues.folio.org/browse/MODAUD-131) - Circ log: display "-" if user does not have barcode
Sometimes user does not have barcode and Circulation log displays nothing in the User barcode column.
Iterate over log records and replace null with "-" in the userBarcode fields. 
Ideally all of the PRs involved in breaking changes would be …
> MODAUD-131 - Circ log: display "-" if user does not have barcode

- pom.xml
[MODAUD-133](https://issues.folio.org/browse/MODAUD-133) - mod-audit: Upgrade RAML Module Builder
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> MODAUD-133 - mod-audit: Upgrade RAML Module Builder

- NEWS.md
- mod-audit-server/pom.xml
- pom.xml
[MODAUD-125](https://issues.folio.org/browse/MODAUD-125) - MODAUD (mod-audit) Nolana release
> MODAUD-125 - Release 2.6.0

- mod-audit-server/src/main/java/org/folio/builder/description/DescriptionHelper.java
- mod-audit-server/src/main/java/org/folio/builder/description/RequestDescriptionBuilder.java
- mod-audit-server/src/test/java/org/folio/builder/service/RequestRecordBuilderTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditHandlersImplApiTest.java
- mod-audit-server/src/test/resources/payloads/request_edited.json
[MODAUD-148](https://issues.folio.org/browse/MODAUD-148) - Edited request record is not correctly stored in the Circulation log 
Fix the problem when edited request record is not correctly stored in the Circulation log
Fix time comparison that produced NPE in case old date was empty.
Ideally all of the PRs involved in breaking changes would be merged in …
> MODAUD-148 - Edited request record is not correctly stored in the Circulation log

- NEWS.md
- mod-audit-server/pom.xml
- mod-audit-server/src/main/java/org/folio/builder/description/DescriptionHelper.java
- mod-audit-server/src/main/java/org/folio/builder/description/RequestDescriptionBuilder.java
- mod-audit-server/src/test/java/org/folio/builder/service/RequestRecordBuilderTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditHandlersImplApiTest.java
- mod-audit-server/src/test/resources/payloads/request_edited.json
- pom.xml
[MODAUD-150](https://issues.folio.org/browse/MODAUD-150) - Release 2.6.1
> MODAUD-150 - Release 2.6.1

- descriptors/ModuleDescriptor-template.json
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> MODAUD-152 bump up inventory interface

- PULL_REQUEST_TEMPLATE.md
- mod-audit-server/src/main/resources/log4j2.properties
MODAUD-137(https://issues.folio.org/browse/MODAUD-137) 
Logging improvement - Configuration
1. log4j.properties file updated to default configuration from folio-spring-base
3. "Check logging" added to PULL_REQUEST_TEMPLATE.md
> [MODAUD-137]: logging improvement

- NEWS.md
- mod-audit-server/pom.xml
- pom.xml
[MODAUD-156] https://issues.folio.org/browse/MODAUD-156
1. Release v2.7.0
> Release 2.7.0

- mod-audit-server/src/main/java/org/folio/builder/service/AbstractNoticeRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/CheckInRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/CheckOutRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/FeeFineRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/LoanRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/ManualBlockRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/NoticeErrorRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/builder/service/RequestRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/dao/acquisition/impl/OrderEventsDaoImpl.java
- mod-audit-server/src/main/java/org/folio/dao/acquisition/impl/OrderLineEventsDaoImpl.java
- mod-audit-server/src/main/java/org/folio/rest/impl/AuditDataAcquisitionImpl.java
- mod-audit-server/src/main/java/org/folio/rest/impl/AuditDataImpl.java
- mod-audit-server/src/main/java/org/folio/rest/impl/AuditHandlersService.java
- mod-audit-server/src/main/java/org/folio/rest/impl/BaseService.java
- mod-audit-server/src/main/java/org/folio/rest/impl/CirculationLogsService.java
- mod-audit-server/src/main/java/org/folio/rest/impl/InitAPIs.java
- mod-audit-server/src/main/java/org/folio/rest/impl/ModTenantService.java
- mod-audit-server/src/main/java/org/folio/services/acquisition/impl/OrderAuditEventsServiceImpl.java
- mod-audit-server/src/main/java/org/folio/services/acquisition/impl/OrderLineAuditEventsServiceImpl.java
- mod-audit-server/src/main/java/org/folio/verticle/acquisition/consumers/OrderEventsHandler.java
- mod-audit-server/src/main/java/org/folio/verticle/acquisition/consumers/OrderLineEventsHandler.java
MODAUD-110 (https://issues.folio.org/browse/MODAUD-110) 
Adding loggers as part of logging improvements
_By following the practices mentioned in https://wiki.folio.org/display/DD/Logging,
Added loggers wherever needed._
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> MODAUD-110 Logging Improvement

- ramls/schemas/action_type.json
- Adding "Staff info added", "Patron info added"
See CIRC-1823. When adding staff info or patron info to loan the log record must be persisted in circulation log. 
Extending enum of valid action types in schema
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> MODAUD-164 - Allow action types for loan info

- mod-audit-server/pom.xml
[MODAUD-167](https://issues.folio.org/browse/MODAUD-167) : Upgrade folio-kafka-wrapper to 3.0.0 version
Upgrade the version of folio-kafka-wrapper to 3.0.0. Check out the readme at https://github.com/folio-org/folio-kafka-wrapper/blob/master/README.md for usage.
changed the version of folio-kafka-wrapper to 3.0.0 in the mod-autid-server/pom.xml
Ideally …
> MODAUD-167 : Upgrade folio-kafka-wrapper to 3.0.0 version

- mod-audit-server/src/main/java/org/folio/builder/service/LoanRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/rest/impl/AuditHandlersService.java
- mod-audit-server/src/test/java/org/folio/builder/service/LoanRecordBuilderTest.java
- mod-audit-server/src/test/resources/payloads/loan_changed_due_date.json
Resolves - [MODAUD-168](https://issues.folio.org/browse/MODAUD-168)
The Purpose is this PR is to show the right patron's name for the circ action: change due date.
Removed the condition check for circ action: "change due date" because for this circ action we need updatedUserId to show the right patron's name in the circulation logs but currently it is using the userId.
If we use the userId for circ action: "change due date" we will get the wrong patron's name (name of the patron who checked out an item) in the circulation logs.
So removed the condition check and fixed test cases.
If there are …
> MODAUD-168

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- mod-audit-server/pom.xml
- pom.xml
Poppy release.
While it's helpful for reviewers to help identify potential problems, …
> MODAUD-173 - Poppy release.

- mod-audit-server/src/main/java/org/folio/builder/description/LoanCheckInDescriptionBuilder.java
- mod-audit-server/src/main/java/org/folio/util/LogEventPayloadField.java
- mod-audit-server/src/test/java/org/folio/builder/service/CheckInRecordBuilderTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditHandlersImplApiTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/CirculationLogsImplApiTest.java
- mod-audit-server/src/test/java/org/folio/utils/TenantApiTestUtil.java
- mod-audit-server/src/test/resources/payloads/check_in.json
- mod-audit-server/src/test/resources/payloads/check_in_with_backdate_timezone.json
- mod-audit-server/src/test/resources/payloads/check_in_with_timezone.json
The purpose of this PR is to fix the issue reported in MODAUD-176. The return and system return date were compared with each other without considering the tenant's timezone. 
To fix this issue the tenant's time zone is now considered to convert the dates and then compare it before putting backdate description in the circulation log.
Ideally all of the …
> MODAUD-176 - Check-ins are automatically backdated to 5 hours later (DUNY/Dominican)

- mod-audit-server/src/main/java/org/folio/dao/acquisition/impl/PieceEventsDaoImpl.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditDataAcquisitionAPITest.java
- mod-audit-server/src/test/java/org/folio/utils/EntityUtils.java
https://issues.folio.org/secure/RapidBoard.jspa?rapidView=77
added also check 'receivingStatus' for api
Output
`http://localhost:9130/audit-data/acquisition/piece/367620f9-f000-47c8-855e-de942bea1bff/status-change-history`
```
{
"pieceAuditEvents": [
{
"id": "d6211689-2606-4e5a-a124-89035a2fb071",
"action": "Edit",
"pieceId": "367620f9-f000-47c8-855e-de942bea1bff",
"userId": "b9b03547-a18a-55fe-b509-1d8fc42da3df",
"eventDate": "2024-01-31T12:01:48.898+00:00",
"actionDate": "2024-01-31T12:01:48.895+00:00",
"pieceSnapshot": {
"map": {
"id": "367620f9-f000-47c8-855e-de942bea1bff",
"format": "Physical",
"caption": "gfgf",
"titleId": "03318ddb-59d4-42ff-b8ff-1f52d3419afd",
"poLineId": "ee0b9edb-5508-5f3e-a33b-0adb42fdcdc5",
"holdingId": "97dd5996-896f-4a0c-acf7-2566bbd6d7fa",
"copyNumber": …
```
> [MODAUD-180] - Modify SQL query for /status-change-history to return records if claimingInterval changed

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- mod-audit-server/pom.xml
- mod-audit-server/src/main/java/org/folio/verticle/acquisition/PieceEventConsumersVerticle.java
- pom.xml
For Q release
While it's helpful for reviewers to help identify potential problems, …
> Q Release 2.9.0

- descriptors/ModuleDescriptor-template.json
To upgrade the holdings-storage version.
While it's helpful for reviewers to help …
> MODAUD-186 - API version update holdings-storage.

- descriptors/ModuleDescriptor-template.json
inventory version upgraded to 14.0
While it's helpful for reviewers to help identify …
> MODAUD-189 - inventory API version update

- NEWS.md
- descriptors/ModuleDescriptor-template.json
[MODAUD-190](https://folio-org.atlassian.net/browse/MODAUD-190)
Upgrade the API version in the ModuleDescriptor-template.json:
-`holdings-storage 8.0`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
> MODAUD-190 - Upgrade "holdings-storage" API

- descriptors/ModuleDescriptor-template.json
- pom.xml
The purpose is to fix the permissions as per MODAUD-187.
The module-descriptor file was fixed.
This PR needs to merge as well - https://github.com/folio-org/mod-pubsub/pull/270
https://github.com/search?q=repo%3Afolio-org%2Fui-receiving+status-change-history&type=code
CC: @Terala-Priyanka 
Ideally all of the PRs involved in breaking changes would be …
> MODAUD-187 - Updating permissions in MD

- .github/workflows/postgres.yml
- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
Upgrade the rmb version in this module.
While it's helpful for reviewers to help …
> MODAUD-192 - Upgrading RMB version to 35.3.0

- descriptors/ModuleDescriptor-template.json
- pom.xml
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> Revert permission changes for MODPUBSUB-301

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- mod-audit-server/pom.xml
- pom.xml
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> To release 2.10.1

- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/rest/impl/AuditHandlersService.java
Change the level of logs from INFO to DEBUG for PII
While it's helpful for reviewers to …
> MODAUD-216 - Remove PII from mod-audit logs

- NEWS.md
- mod-audit-server/pom.xml
- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/rest/impl/AuditHandlersService.java
- pom.xml
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> To release 2.10.2

- descriptors/ModuleDescriptor-template.json
- mod-audit-server/src/main/java/org/folio/dao/inventory/impl/HoldingsEventDao.java
- mod-audit-server/src/main/java/org/folio/dao/inventory/impl/ItemEventDao.java
- mod-audit-server/src/main/java/org/folio/rest/impl/InventoryAuditImpl.java
- mod-audit-server/src/test/java/org/folio/rest/impl/InventoryAuditApiTest.java
- ramls/inventory-audit.raml
Implement holdings audit endpoint
[MODAUD-213](https://folio-org.atlassian.net/browse/MODAUD-213)
> feat(inventory-audit): Implement holdings audit endpoint

- descriptors/ModuleDescriptor-template.json
- mod-audit-server/src/main/java/org/folio/rest/impl/AuditConfigImpl.java
- mod-audit-server/src/main/java/org/folio/services/configuration/Setting.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditConfigAPITest.java
https://folio-org.atlassian.net/browse/MODAUD-234
PUT /audit/config/groups/{groupId}/settings/{settingId} endpoint should protect each specific setting.
Modify verification logic
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> feat(config): update request for configuration entries should be protected by separate permissions

- mod-audit-server/src/main/java/org/folio/dao/inventory/InventoryEventDao.java
- mod-audit-server/src/main/java/org/folio/dao/inventory/impl/InventoryEventDaoImpl.java
- mod-audit-server/src/main/java/org/folio/services/inventory/impl/InventoryEventServiceImpl.java
- mod-audit-server/src/test/java/org/folio/rest/impl/InventoryAuditApiTest.java
- mod-audit-server/src/test/java/org/folio/services/inventory/impl/InventoryEventServiceImplTest.java
- ramls/schemas/inventory/inventory_audit_collection.json
Support version counter in Version history pane
https://folio-org.atlassian.net/browse/MODAUD-229
Do count query before records fetching
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> feat(inventory-audit): add totalRecords to collection response

- NEWS.md
- mod-audit-server/src/main/java/org/folio/dao/inventory/InventoryEventDao.java
- mod-audit-server/src/main/java/org/folio/dao/inventory/impl/InventoryEventDaoImpl.java
- mod-audit-server/src/main/java/org/folio/services/inventory/InventoryEventService.java
- mod-audit-server/src/main/java/org/folio/services/inventory/impl/InventoryEventServiceImpl.java
- mod-audit-server/src/main/java/org/folio/util/inventory/InventoryEvent.java
- mod-audit-server/src/main/java/org/folio/util/inventory/InventoryUtils.java
- mod-audit-server/src/main/java/org/folio/verticle/inventory/consumers/InventoryEventHandler.java
- mod-audit-server/src/test/java/org/folio/dao/inventory/impl/InstanceEventDaoTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/InventoryEventHandlerMockTest.java
- mod-audit-server/src/test/java/org/folio/services/inventory/impl/InventoryEventServiceImplTest.java
- mod-audit-server/src/test/java/org/folio/util/inventory/InventoryUtilsTest.java
- mod-audit-server/src/test/java/org/folio/utils/EntityUtils.java
Handle inventory consortium shadow copy events
- ignore event when CREATE consortium shadow copy event
- delete all records by entityId when UPDATE/DELETE consortium shadow copy event
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …
> feat(inventory-audit): Handle inventory shadow copy events

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- mod-audit-server/src/main/java/org/folio/dao/inventory/InventoryEventDao.java
- mod-audit-server/src/main/java/org/folio/dao/inventory/impl/InventoryEventDaoImpl.java
- mod-audit-server/src/main/java/org/folio/dao/marc/MarcAuditDao.java
- mod-audit-server/src/main/java/org/folio/dao/marc/impl/MarcAuditDaoImpl.java
- mod-audit-server/src/main/java/org/folio/rest/impl/AuditDataCleanupImpl.java
- mod-audit-server/src/main/java/org/folio/services/inventory/InventoryEventService.java
- mod-audit-server/src/main/java/org/folio/services/inventory/impl/InventoryEventServiceImpl.java
- mod-audit-server/src/main/java/org/folio/services/management/AuditManager.java
- mod-audit-server/src/main/java/org/folio/services/marc/MarcAuditService.java
- mod-audit-server/src/main/java/org/folio/services/marc/impl/MarcAuditServiceImpl.java
- mod-audit-server/src/test/java/org/folio/TestSuite.java
- mod-audit-server/src/test/java/org/folio/dao/inventory/impl/InstanceEventDaoTest.java
- mod-audit-server/src/test/java/org/folio/dao/marc/impl/MarcAuditDaoTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditDataCleanupApiTest.java
- mod-audit-server/src/test/java/org/folio/services/inventory/impl/InventoryEventServiceImplTest.java
- mod-audit-server/src/test/java/org/folio/services/management/AuditManagerTest.java
- mod-audit-server/src/test/java/org/folio/services/marc/impl/MarcAuditServiceTest.java
- ramls/audit-cleanup.raml
Implement scheduled job for audit cleanup, implement audit expiration part
Implement MARC/inventory audit records expiration using okapi timer interface to run everyday at 2am UTC
[Timer docs](https://github.com/folio-org/okapi/blob/master/doc/guide.md#timer-interface)
> feat(cleanup): Implement scheduled job for audit cleanup

- mod-audit-server/src/main/java/org/folio/dao/marc/MarcAuditDao.java
- mod-audit-server/src/main/java/org/folio/dao/marc/impl/MarcAuditDaoImpl.java
- mod-audit-server/src/main/java/org/folio/services/marc/impl/MarcAuditServiceImpl.java
- mod-audit-server/src/test/java/org/folio/dao/marc/impl/MarcAuditDaoTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/MarcAuditApiTest.java
- mod-audit-server/src/test/java/org/folio/services/marc/impl/MarcAuditServiceTest.java
- ramls/schemas/marc/marc_audit_collection.json
[MODAUD-236](https://folio-org.atlassian.net/browse/MODAUD-236)
Support version counter in Version history pane for MARC records
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> MODAUD-236 Add totalRecord counter to the /audit-data/marc API responses

- descriptors/ModuleDescriptor-template.json
Desired permissions not passing to module during request on Eureka platform.
Modify the desired permission pattern to have * at the end, because Eureka supports only this case. 
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
> fix(config): modify desired permission pattern

- NEWS.md
- mod-audit-server/src/main/java/org/folio/dao/inventory/InventoryEventDao.java
- mod-audit-server/src/main/java/org/folio/dao/inventory/impl/InstanceEventDao.java
- mod-audit-server/src/main/java/org/folio/dao/inventory/impl/InventoryEventDaoImpl.java
- mod-audit-server/src/main/java/org/folio/dao/management/PartitionDao.java
- mod-audit-server/src/main/java/org/folio/dao/marc/MarcAuditDao.java
- mod-audit-server/src/main/java/org/folio/dao/marc/impl/MarcAuditDaoImpl.java
- mod-audit-server/src/main/java/org/folio/services/inventory/impl/InventoryEventServiceImpl.java
- mod-audit-server/src/main/java/org/folio/services/management/AuditManager.java
- mod-audit-server/src/main/java/org/folio/services/management/DatabaseSubPartition.java
- mod-audit-server/src/main/java/org/folio/services/management/PartitionService.java
- mod-audit-server/src/main/java/org/folio/services/management/YearQuarter.java
- mod-audit-server/src/test/java/org/folio/dao/inventory/impl/InstanceEventDaoTest.java
- mod-audit-server/src/test/java/org/folio/dao/management/PartitionDaoTest.java
- mod-audit-server/src/test/java/org/folio/dao/marc/impl/MarcAuditDaoTest.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditDataCleanupApiTest.java
- mod-audit-server/src/test/java/org/folio/services/management/AuditManagerTest.java
- mod-audit-server/src/test/java/org/folio/services/management/DatabaseSubPartitionTest.java
- mod-audit-server/src/test/java/org/folio/services/management/PartitionServiceTest.java
- mod-audit-server/src/test/java/org/folio/services/management/YearQuarterTest.java
Extend scheduled job with old empty partitions deletion, new partitions creation
- Query empty sub partitions from databse
- Delete partitions for previous quarters
- Create partitions for next quarter if empty
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> feat(cleanup): Extend scheduled job with old empty partitions deletion, new partitions creation

- mod-audit-server/src/main/java/org/folio/dao/management/PartitionDao.java
- mod-audit-server/src/main/java/org/folio/services/management/PartitionService.java
- mod-audit-server/src/test/java/org/folio/dao/management/PartitionDaoTest.java
Fix handling absence of sub-partitions to delete, existing future sub-partitions
[MODAUD-235](https://folio-org.atlassian.net/browse/MODAUD-235)
Add null/empty checks
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
> fix(cleanup): Fix handling absence of sub-partitions to delete, existing future sub-partitions

- mod-audit-server/src/main/java/org/folio/dao/marc/MarcAuditEntity.java
- mod-audit-server/src/main/java/org/folio/dao/marc/impl/MarcAuditDaoImpl.java
- mod-audit-server/src/main/java/org/folio/services/marc/impl/MarcAuditServiceImpl.java
- mod-audit-server/src/main/java/org/folio/util/marc/MarcUtil.java
- mod-audit-server/src/test/java/org/folio/rest/impl/MarcAuditApiTest.java
- mod-audit-server/src/test/java/org/folio/util/marc/MarcUtilTest.java
- ramls/schemas/marc/marc_audit_item.json
* **MARC Diff Structure Alignment:** The structure of the MARC diff response has been modified to mirror the structure used in Inventory diffs.
* **Subfield Key Spacing:** Spaces have been added before and after subfield keys within the diff output (e.g., `ind$avalue` will now be `ind $a value`).
* **Event Timestamp (eventTs) Addition:** The `eventTs` (event timestamp) field has been added to the response. 
- Are the JIRAs under …
> MODAUD-238 Make adjustments for MARC diff structure

- mod-audit-server/src/main/java/org/folio/util/marc/MarcUtil.java
- mod-audit-server/src/test/java/org/folio/util/marc/MarcUtilTest.java
[MODAUD-240](https://folio-org.atlassian.net/browse/MODAUD-240)
In the MARC authority record audit log, a change is being recorded due to the $i and $s of the 999 being switched. The subfields order should not change and an audit log entry of “Updated” should not be included.
Ignore modification in 999ff
Ideally all of the PRs involved in breaking …
> MODAUD-240 Ignore modification in 999ff

- README.md
- ramls/examples/configuration/setting_collection_sample.json
- ramls/examples/configuration/setting_sample.json
Add documentation for Audit Configuration APIs
update README.md
Closes: [MODAUD-254](https://folio-org.atlassian.net/browse/MODAUD-254)
> MODAUD-254: Add documentation for Audit Configuration APIs

- NEWS.md
- descriptors/ModuleDescriptor-template.json
`item-storage` API has breaking change and version change. Bump the optional `item-storage` dependency version in `mod-audit` 
- bump `item-storage` dependency version in descriptor
Closes: [MODAUD-265](https://folio-org.atlassian.net/browse/MODAUD-265)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking …
> MODAUD-265: Bump Item Storage Api version
