folio-org/mod-audit

- ramls/audit.json
Adding "method" attribute to the json schema so cql queries work as expected.
> add method attribute to the json schema

- descriptors/ModuleDescriptor-template.json
Enables ready default deployment.
Refer to [FOLIO-2235](https://issues.folio.org/browse/FOLIO-2235) and [documentation](https://dev.folio.org/guides/module-descriptor/#launchdescriptor-properties).
Review is not needed. This is a devops task: Doing similar for all modules.
> Add default LaunchDescriptor settings FOLIO-2235

- Dockerfile
- descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
> MODAUD-6 FOLIO-2358 manage container memory

- mod-audit-server/pom.xml
Simple change to get rid of `ERROR StatusLogger Unrecognized format` in the log.
> MODAUD-37: Fix ERROR StatusLogger Unrecognized format

- NEWS.md
[MODAUD-40](https://issues.folio.org/browse/MODAUD-40) - Bugfix release 1.0.3
> MODAUD-40 - Release 1.0.3 (backport to master)

- mod-audit-server/src/main/java/org/folio/builder/service/LoanRecordBuilder.java
- mod-audit-server/src/test/java/org/folio/builder/service/LoanRecordBuilderTest.java
[MODAUD-50](https://issues.folio.org/browse/MODAUD-50) - Update Age to lost data in Circulation log
The Age to lost filter should NOT show Service point data since it is an automated process
Service point data is being removed for Age to lost loan actions
Verified on local test env:
Ideally all of the PRs involved in breaking changes would be merged in …
> MODAUD-50 - Update Age to lost data in Circulation log

- mod-audit-server/src/main/resources/templates/db_scripts/schema.json
[MODAUD-69](https://issues.folio.org/browse/MODAUD-69) - mod_audit.circulation_logs query utilizing excessive DB CPU
Improve CPU utilizating due to using of RMB ginIndex.
Changing items index from ginIndex to fullTextIndex. Previously identified by @sduvvuri-ebsco @evaluk and @hjiebsco  that changing of ginIndex:
```
CREATE INDEX circulation_logs_items_idx_gin
ON fs00001034_mod_audit.circulation_logs USING gin
(lower(fs00001034_mod_audit.f_unaccent(jsonb ->> 'items'::text)) COLLATE pg_catalog."default" gin_trgm_ops) TABLESPACE pg_default;
```
to fullTextIndex
```
CREATE INDEX circulation_logs_items_idx_2
ON fs00001034_mod_audit.circulation_logs USING gin
(fs00001034_mod_audit.get_tsvector(fs00001034_mod_audit.f_unaccent(jsonb ->> 'items'::text)))TABLESPACE pg_default;
```
significantly …
> MODAUD-69 - mod_audit.circulation_logs query utilizing excessive DB CPU

- mod-audit-server/src/main/java/org/folio/rest/impl/AuditDataImpl.java
- mod-audit-server/src/test/java/org/folio/rest/impl/AuditDataImplApiTest.java
ExtendedAsyncResult from okapi-common has been deleted:
https://issues.folio.org/browse/OKAPI-1078
https://issues.folio.org/browse/OKAPI-810
A solution that much better works with Future is ErrorTypeException from okapi-common.
Okapi >= 5.0.0 will ship without ExtendedAsyncResult.
mod-audit uses ExtendedAsyncResult only in AuditDataImpl.
The code in AuditDataImpl can be replaced by the default code provided by RMB's PgUtil.
Task:
Replace ExtendedAsyncResult by ErrorTypeException, or replace AuditDataImpl code by PgUtil.
Replace ExtendedAsyncResult.
https://issues.folio.org/browse/MODAUD-113
Replace AuditDataImpl code by RMB's PgUtil default methods.
none
Using PgUtil is much easier than maintaining own code.
Before merging this PR, please go through the following list and take appropriate …
> MODAUD-113: Replace ExtendedAsyncResult by PgUtil in AuditDataImpl

- mod-audit-server/pom.xml
- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/rest/impl/AuditHandlersService.java
- pom.xml
[MODAUD-121](https://issues.folio.org/browse/MODAUD-121) - mod-audit - Remove vertx-completable-future for Morning Glory (2022 R2)
Remove any usage of the
me.escoffier.vertx:vertx-completable-future = https://github.com/cescoffier/vertx-completable-future library because it is no longer maintained and doesn't work with Vert.x 4.
Use java.util.concurrent.CompletableFuture instead.
- Do …
> MODAUD-121 - mod-audit - Remove vertx-completable-future for Morning Glory (2022 R2)

- mod-audit-server/src/test/resources/mocks/one-user-collection.json
- ramls/schemas/external/user.json
[MODAUD-123](https://issues.folio.org/browse/MODAUD-123) - Notice events for users with tags does not appear in circulation log
When performing circulation-specific actions, notice events for users with tags does not appear in circulation log.
* Fixed user schema
* Updated unit tests
Ideally all of the PRs involved in breaking changes would be merged in …
> MODAUD-123 - Notice events for users with tags does not appear in circulation log

- descriptors/ModuleDescriptor-template.json
mod-inventory-storage has new major interface versions:
instance-storage 9.0
holdings-storage 6.0
item-storage 10.0
mod-audit only uses the holdings-storage interfaces, it doesn't use the two other interfaces.
mod-audit is not affected because the incompatible change is in the DELETE all APIs only that is not used by mod-audit.
Only the okapiInterfaces need to be bumped in "requires" section of ModuleDescriptor-template.json
> MODAUD-129: Support holdings-storage 6.0 interface

- descriptors/ModuleDescriptor-template.json
Fix a [broken module descriptor](https://jenkins-aws.indexdata.com/job/folio-org/job/mod-audit/job/master/129) due to a comma separating the expected versions of the `users` interface.
> Remove comma from user interface expectations list MODAUD-128

- mod-audit-server/pom.xml
Upgrade com.jayway.jsonpath:json-path from 2.5.0 to 2.7.0. This indirectly upgrades net.minidev:json-smart from 2.3 to 2.4.7 fixing Denial of Service (DoS): https://nvd.nist.gov/vuln/detail/cve-2021-27568
Adding <scope>test</scope> as json-path/json-smart is used in tests only.
https://issues.folio.org/browse/MODAUD-135
json-path 2.7.0 has been available since Jan 30, 2022.
mod-audit should have upgraded its dependencies for [mod-audit v2.3.0](https://github.com/folio-org/mod-audit/releases/tag/v2.3.0) released Feb 23, 2022 and for [mod-audit v2.4.0](https://github.com/folio-org/mod-audit/releases/tag/v2.4.0) released May 23, 2022 and for [mod-audit v2.5.0](https://github.com/folio-org/mod-audit/releases/tag/v2.5.0) released Jul 08, 2022.
Please upgrade all dependencies before making the …
> MODAUD-135: json-path 2.7.0 fixing json-smart DoS CVE-2021-27568

- mod-audit-server/src/main/resources/templates/db_scripts/acquisition/create_acquisition_order_line_log_table.sql
- mod-audit-server/src/main/resources/templates/db_scripts/acquisition/create_acquisition_order_log_table.sql
- mod-audit-server/src/main/resources/templates/db_scripts/schema.json
https://issues.folio.org/browse/MODAUD-140
Related doc that describes schema: https://wiki.folio.org/display/DD/Orders+Event+Log 
Created locally acquisition_order_line_log table:
Created locally acquisition_order_log table:
> MODAUD-140. Create tables to store audit logs for orders and order lines

- .github/workflows/api-doc.yml
- .github/workflows/api-lint.yml
- .github/workflows/api-schema-lint.yml
- Jenkinsfile
- README.md
- ramls/audit-data.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
> FOLIO-3678 MODAUD-161 Use GitHub Workflows api-lint and api-schema-lint and api-doc

- descriptors/ModuleDescriptor-template.json
- mod-audit-server/src/main/java/org/folio/builder/service/LogRecordBuilder.java
- mod-audit-server/src/main/java/org/folio/util/Constants.java
- mod-audit-server/src/test/java/org/folio/rest/impl/CirculationLogsImplApiTest.java
- mod-audit-server/src/test/java/org/folio/utils/TenantApiTestUtil.java
- mod-audit-server/src/test/resources/mock_content.json
- mod-audit-server/src/test/resources/mocks/circulation-item.json
- mod-audit-server/src/test/resources/payloads/fee_fine_billed_automated_virtual_item.json
The purpose of the jira is to implement MODAUD-177
If the log records is posted for a virtual item with action fee/fine , then InstanceId and holdingsId is not returned whenever they are retrieved in Circ log. Since the virtual item is not present in the inventory, it returns 404 and  the subsequent call to holdings storage and instance storage is not happening. In order to fix this, whenever the itemObject is null, we will look into the circulation-item module to retrieve its data.
**Evidence**
- What other modules will …
> MODAUD-177 Added the virtual item lookup if item is missed in Inventory

- mod-audit-server/src/main/java/org/folio/mapper/InventoryEventToEntityMapper.java
- mod-audit-server/src/main/java/org/folio/services/diff/DiffCalculator.java
- mod-audit-server/src/main/java/org/folio/services/diff/HoldingsDiffCalculator.java
- mod-audit-server/src/main/java/org/folio/services/diff/InstanceDiffCalculator.java
- mod-audit-server/src/main/java/org/folio/services/diff/ItemDiffCalculator.java
- mod-audit-server/src/test/java/org/folio/mapper/InventoryEventToEntityMapperTest.java
- mod-audit-server/src/test/java/org/folio/services/diff/DiffCalculatorTest.java
- mod-audit-server/src/test/java/org/folio/services/diff/HoldingsDiffCalculatorTest.java
- mod-audit-server/src/test/java/org/folio/services/diff/InstanceDiffCalculatorTest.java
- mod-audit-server/src/test/java/org/folio/services/diff/ItemDiffCalculatorTest.java
Handle issues in diff calculation. 
Related to https://folio-org.atlassian.net/browse/MODAUD-219
- Fix handling case when there is no difference between records
- Fix handling inner object field diff calculation:
- Add `access` method to make it possible to do changes to a record before diff calculation
- Init inner object fields with empty objects …
> fix(inventory-audit): adjust diff calculation

- NEWS.md
- mod-audit-server/src/main/java/org/folio/util/marc/SourceRecordType.java
- mod-audit-server/src/main/java/org/folio/verticle/marc/consumers/MarcRecordEventsHandler.java
- mod-audit-server/src/test/java/org/folio/rest/impl/MarcRecordEventsHandlerMockTest.java
to ensure marc records events processing and marc records audit data saving 
* extend SourceRecordType enum to avoid error during event handling and add conditional check for MARC_HOLDING record types to skip audit data saving for such events
[MODAUD-250](https://issues.folio.org/browse/MODAUD-250)
> MODAUD-250 - Version history of "MARC" records is not tracked

- mod-audit-server/src/main/resources/templates/db_scripts/acquisition/update_to_orders_storage_14.0.ftl
- mod-audit-server/src/main/resources/templates/db_scripts/schema.json
- [MODORDSTOR-448](https://folio-org.atlassian.net/browse/MODORDSTOR-448) - Make user limit as string field & apply migration
- [MODORDERS-1269](https://folio-org.atlassian.net/browse/MODORDERS-1269) - Remove alerts and reporting codes from order lines, use a single order line schema
Added a migration script.
- [MODORDSTOR-448 main PR](https://github.com/folio-org/mod-orders-storage/pull/476)
- [MODORDERS-1269 main PR](https://github.com/folio-org/mod-orders-storage/pull/477)
- …
> [MODORDSTOR-448] Update po lines to orders-storage 14.0

- NEWS.md
- mod-audit-server/pom.xml
- mod-audit-server/src/main/resources/templates/db_scripts/schema.json
- pom.xml
Set back the current development iteration as v3.0.0-SNAPSHOT after it was already set as v3.0.0-SNAPSHOT, but then modified to v2.12.0-SNAPSHOT
Set back and prepare next development release iteration as 3.0.0-SNAPSHOT
[MODAUD-259](https://folio-org.atlassian.net/browse/MODAUD-259)
> MODAUD-259: Revert back and prepare next development release iteration as 3.0.0
